### PR TITLE
BRS-924: Missing text on park edit page

### PR DESCRIPTION
**Pull request by JLWade**
### Jira Ticket:
BRS-924

### Jira Ticket URL:
https://bcparksdigital.atlassian.net/browse/BRS-924

### Description:
Add missing text from park edit page - Jess's First PR!

### CODE REVIEW

**Review by cameronpettit — APPROVED** [review]

**Review by marklise — APPROVED** [review]
👍

**Comment by danieltruong** [comment]
UM, you didn't write accompanying documentation for this code! REJECTED!

JK

**Review by danieltruong — APPROVED** [review]

**Review by meredithom — APPROVED** [review]
🙌

**Comment by JLWade** [comment]
Documentation on it's way! ;)

**Pull request merged**
